
function DataService(){this.all=function(type){var all=[];for(var id in localStorage){if(id.match(new RegExp("^"+type.name.toLowerCase()+"\.[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$"))){all.push(this.load(type,id));}}
return all;};this.load=function(type,id){return new type(id,angular.fromJson(localStorage.getItem(id)));};this.save=function(obj){localStorage.setItem(obj.id,angular.toJson(obj.persistentData()));return obj;};var migrations={null:function(){var data;for(var name in localStorage){data=angular.fromJson(localStorage.getItem(name));data.name=name;localStorage.setItem("inputs."+uuid(),angular.toJson(data));localStorage.removeItem(name);}
return"1";},1:function(){var match,data;for(var id in localStorage){match=id.match(/^inputs\.([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})$/)
if(match){data=localStorage.getItem(id);localStorage.setItem("cost."+match[1],data);localStorage.removeItem(id);}}
return"2";},2:function(){var match,data,costData,paymentData;for(var id in localStorage){match=id.match(/^cost\.[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$/)
if(match){data=angular.fromJson(localStorage.getItem(id));costData={};paymentData={};for(var key in data){if(["capital","interestRate","amortizationRate"].indexOf(key)==-1){costData[key]=data[key];}else{paymentData[key]=data[key];}}
paymentData.name=data.name;localStorage.setItem(id,angular.toJson(costData));localStorage.setItem("payment."+uuid(),angular.toJson(paymentData));}}
return"3";}};this.migrate=function(){var schemaVersion=localStorage.getItem("schemaVersion"),migration,newSchemaVersion;do{migration=migrations[schemaVersion];if(migration===undefined){break;}
newSchemaVersion=migration();console.log("migrated schema from version "+schemaVersion+" to version "+newSchemaVersion);schemaVersion=newSchemaVersion;}while(true);if(schemaVersion)
localStorage.setItem("schemaVersion",schemaVersion);};this.migrate();}
function makePersistable(defaults){this.defaults=defaults;this.persistentData=function(){persistentData={};for(key in defaults){persistentData[key]=this[key];}
return persistentData;}}
function Cost(id,persistentData){this.id=id||"cost."+uuid();angular.extend(this,this.defaults);angular.extend(this,persistentData);}
Cost.prototype.brokerageCost=function(){return this.price*this.brokerage/100.0;};Cost.prototype.taxCost=function(){return this.price*this.tax/100.0;};Cost.prototype.notaryCost=function(){return this.price*this.notary/100.0;};Cost.prototype.cost=function(){return this.price+this.brokerageCost()+this.taxCost()+this.notaryCost()+this.addOns;};makePersistable.call(Cost.prototype,{name:"Unbenannt",price:450000.0,brokerage:6.25,tax:5.0,notary:1.5,addOns:0.0,});function Month(balance,payment,interestRate){this.balance=balance;this.interestRate=interestRate;this.interest=Math.round(this.balance*this.interestRate/12*100)/100.0;this.amortization=Math.min(payment-this.interest,this.balance);this.payment=this.interest+this.amortization;this.remainder=this.balance-this.amortization;}
function Payment(id,persistentData){this.id=id||"payment."+uuid();angular.extend(this,this.defaults);angular.extend(this,persistentData);}
Payment.prototype.paymentRate=function(){return this.interestRate+this.amortizationRate;};makePersistable.call(Payment.prototype,{name:"Unbenannt",capital:100000.0,interestRate:3.0,amortizationRate:1.0,});function InterestCtrl($scope,$timeout,dataService){$scope.addCost=function(){var cost=new Cost();dataService.save(cost);$scope.costs.push(cost);$scope.selectCost($scope.costs.length-1);};$scope.selectCost=function(index){$scope.selectedCost=$scope.costs[index];return $scope.selectedCost;}
$scope.saveCost=function(){dataService.save($scope.selectedCost);};$scope.addPayment=function(){var payment=new Payment();dataService.save(payment);$scope.payments.push(payment);$scope.selectPayment($scope.payments.length-1);};$scope.selectPayment=function(index){$scope.selectedPayment=$scope.payments[index];return $scope.selectPayment;}
$scope.savePayment=function(){dataService.save($scope.selectedPayment);};$scope.credit=function(){return $scope.selectedCost.cost()-$scope.selectedPayment.capital;};$scope.payment=function(){var yearlyPayment=$scope.credit()*$scope.selectedPayment.paymentRate()/100.0;return Math.round(yearlyPayment/12);};var calculationTimer,processData;$scope.calculate=function(){$timeout.cancel(calculationTimer);$scope.saveCost();$scope.savePayment();$scope.months=null;$scope.processing=true;processData={months:[],month:null,balance:$scope.credit(),};calculationTimer=$timeout(processNextMonth,100);};function processNextMonth(times){times=times||0;if(processData.balance>0){var month=new Month(processData.balance,$scope.payment(),$scope.selectedPayment.interestRate/100.0);processData.balance=month.remainder;processData.months.push(month);if(times<6){processNextMonth(times+1);}else{calculationTimer=$timeout(processNextMonth,0);}}else{$scope.totalInterest=0;$scope.totalPayments=0;for(var month in processData.months){$scope.totalInterest+=processData.months[month].interest;$scope.totalPayments+=processData.months[month].payment;};$scope.months=processData.months;$scope.processing=false;processData=null;}}
$scope.costs=dataService.all(Cost);if($scope.costs.length==0){$scope.addCost();}
$scope.selectCost(0);$scope.payments=dataService.all(Payment);if($scope.payments.length==0){$scope.addPayment();}
$scope.selectPayment(0);$scope.calculate();}
var app=angular.module("app",[]);app.service("dataService",DataService);app.controller("interestCtrl",InterestCtrl);function uuid(){var s4=function(){return Math.floor((1+Math.random())*0x10000).toString(16).substring(1);};return s4()+s4()+'-'+s4()+'-'+s4()+'-'+
s4()+'-'+s4()+s4()+s4();}