
function DataService(){this.all=function(){var all=[];for(var id in localStorage){if(id.match(/^inputs\.[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$/))
all.push(this.load(id));}
return all;};this.load=function(id){return new Inputs(id,angular.fromJson(localStorage.getItem(id)));};this.save=function(inputs){localStorage.setItem(inputs.id,angular.toJson(inputs.persistentData()));return inputs;};var migrations={null:function(){var data;for(var name in localStorage){data=angular.fromJson(localStorage.getItem(name));data.name=name;localStorage.setItem("inputs."+uuid(),angular.toJson(data));localStorage.removeItem(name);}
return"1";}};this.migrate=function(){var schemaVersion=localStorage.getItem("schemaVersion"),migration,newSchemaVersion;do{migration=migrations[schemaVersion];if(migration===undefined){break;}
newSchemaVersion=migration();console.log("migrated schema from version "+schemaVersion+" to version "+newSchemaVersion);schemaVersion=newSchemaVersion;}while(true);if(schemaVersion)
localStorage.setItem("schemaVersion",schemaVersion);}}
function makePersistable(defaults){this.defaults=defaults;this.persistentData=function(){persistentData={};for(key in defaults){persistentData[key]=this[key];}
return persistentData;}}
function Inputs(id,persistentData){this.id=id||uuid();angular.extend(this,this.defaults);angular.extend(this,persistentData);}
makePersistable.call(Inputs.prototype,{name:"Unbenannt",price:450000.0,brokerage:6.25,tax:5.0,notary:1.5,addOns:0.0,capital:100000.0,interestRate:3.0,amortizationRate:1.0,});function Month(balance,payment,interestRate){this.balance=balance;this.interestRate=interestRate;this.interest=Math.round(this.balance*this.interestRate/12*100)/100.0;this.amortization=Math.min(payment-this.interest,this.balance);this.payment=this.interest+this.amortization;this.remainder=this.balance-this.amortization;}
function Outputs(){}
function InterestCtrl($scope,$timeout,dataService){dataService.migrate();$scope.add=function(){$scope.allInputs.push(new Inputs());$scope.select($scope.allInputs.length-1);};$scope.select=function(index){$scope.inputs=$scope.allInputs[index]
$scope.outputs=new Outputs();$scope.calculate();}
$scope.save=function(){dataService.save($scope.inputs);};var calculationTimer=null;$scope.calculate=function(){$timeout.cancel(calculationTimer);$scope.save();var inputs=$scope.inputs,outputs=$scope.outputs;outputs.brokerageCost=inputs.price*inputs.brokerage/100.0;outputs.taxCost=inputs.price*inputs.tax/100.0;outputs.notaryCost=inputs.price*inputs.notary/100.0;outputs.cost=inputs.price+outputs.brokerageCost+outputs.taxCost+outputs.notaryCost+inputs.addOns;outputs.credit=outputs.cost-inputs.capital;outputs.payment=Math.round(outputs.credit*(inputs.interestRate+inputs.amortizationRate)/12)/100.0;$scope.months=null;$scope.processing={months:[],month:null,balance:outputs.credit,};calculationTimer=$timeout(processNextMonth,100);};function processNextMonth(times){times=times||0;var data=$scope.processing;if(data.balance>0){var month=new Month(data.balance,$scope.outputs.payment,$scope.inputs.interestRate/100.0);data.balance=month.remainder;data.months.push(month);if(times<6){processNextMonth(times+1);}else{calculationTimer=$timeout(processNextMonth,0);}}else{$scope.outputs.totalInterest=0;$scope.outputs.totalPayments=0;for(var month in data.months){$scope.outputs.totalInterest+=data.months[month].interest;$scope.outputs.totalPayments+=data.months[month].payment;};$scope.months=data.months;$scope.processing=null;$scope.$apply();}}
$scope.allInputs=dataService.all();if($scope.allInputs.length==0){$scope.add();}
$scope.select(0);}
var app=angular.module("app",[]);app.service("dataService",DataService);app.controller("interestCtrl",InterestCtrl);function uuid(){var s4=function(){return Math.floor((1+Math.random())*0x10000).toString(16).substring(1);};return s4()+s4()+'-'+s4()+'-'+s4()+'-'+
s4()+'-'+s4()+s4()+s4();}